//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelerate_31327.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AccelerateEntities : DbContext
    {
        public AccelerateEntities()
            : base("name=AccelerateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Details> Employee_Details { get; set; }
        public virtual DbSet<Employee_Skill_Details> Employee_Skill_Details { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Technology_Details> Technology_Details { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
    
        public virtual ObjectResult<GetEmployeeList_Result> GetEmployeeList(string searchText)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeList_Result>("GetEmployeeList", searchTextParameter);
        }
    }
}
