//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelerate_31327.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Skill_Details
    {
        public int Skill_ID { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<int> Technology_ID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Employee_Details Employee_Details { get; set; }
        public virtual Technology_Details Technology_Details { get; set; }
    }
}
